In [2]:
import numpy as np
import pandas as pd
from numpy import linalg as LA
A=np.array([
    [1030, 460, 308, 0, 0]
    ,[207873,360946,419497,255677,231644]
    ,[24098,20289,36651,37299,36331]
    ,[182751,204465,213333,247807,257715]
    ,[26251,29420,43884,38408,38133]
    ,[174890,198527,219699,202881,184766]
    ,[93870,115438,145771,182936,210991]
])
print('Matrix A: The quantities: \n')
print(A)
print(' \n')

B=np.array([
    [6111342,2642346,1625113,0,0]
    ,[1028699017,2018418079,2477308573,1407211854, 1321359762]
    ,[224671842,217543079,306085289,289197547,272226265]
    ,[797288247,1109521158,1133404494,1179388140,1265644208]
    ,[154899522,186463377,279855019,224727249,224072284]
    ,[817077074,997985988,1200336982,918881537,884876984]
    ,[547137064,786799462,1007934832,1012735225,1018182179]
])

print('Matrix B: The dollar values \n')
print(B)
print(' \n')


b=np.array([10378801,8252997285, 1309724022,5485246247,1070017451,4819158565,4372788762])
print('Vector b: Total dollar value of imports by country \n')
print(b)

np.linalg.matrix_rank(A)
np.linalg.matrix_rank(B)

Matrix A: The quantities: 

[[  1030    460    308      0      0]
 [207873 360946 419497 255677 231644]
 [ 24098  20289  36651  37299  36331]
 [182751 204465 213333 247807 257715]
 [ 26251  29420  43884  38408  38133]
 [174890 198527 219699 202881 184766]
 [ 93870 115438 145771 182936 210991]]
 

Matrix B: The dollar values 

[[   6111342    2642346    1625113          0          0]
 [1028699017 2018418079 2477308573 1407211854 1321359762]
 [ 224671842  217543079  306085289  289197547  272226265]
 [ 797288247 1109521158 1133404494 1179388140 1265644208]
 [ 154899522  186463377  279855019  224727249  224072284]
 [ 817077074  997985988 1200336982  918881537  884876984]
 [ 547137064  786799462 1007934832 1012735225 1018182179]]
 

Vector b: Total dollar value of imports by country 

[  10378801 8252997285 1309724022 5485246247 1070017451 4819158565
 4372788762]


5

In [8]:
np.linalg.matrix_rank(A)

5

In [2]:
w, Res, rank, sv=LA.lstsq(A,b)
print('The average price of beef that year across countries \n')
print(w)

The average price of beef that year 

[ 29196.18906129 -31202.21480234  41915.56548473 -58848.48870257
  47034.33386462]


In [6]:
c=np.dot(A,w)
print('The predicted value of imports by country')
print(c)

The predicted value of imports by country
[  2.86290501e+07   8.23925495e+09   1.12057002e+09   5.43623114e+09
   1.22119017e+09   4.87155272e+09   4.40711290e+09]


In [7]:
b-c

array([ -1.82502491e+07,   1.37423384e+07,   1.89154000e+08,
         4.90151059e+07,  -1.51172723e+08,  -5.23941577e+07,
        -3.43241362e+07])

In [9]:
from scipy.optimize import nnls
solution = nnls(A, b)[0]
solution

array([     0.        ,      0.        ,  13819.25719807,      0.        ,
        10404.89894146])

In [6]:
print(A.T)

[[  1030 207873  24098 182751  26251 174890  93870]
 [   460 360946  20289 204465  29420 198527 115438]
 [   308 419497  36651 213333  43884 219699 145771]
 [     0 255677  37299 247807  38408 202881 182936]
 [     0 231644  36331 257715  38133 184766 210991]]


In [37]:
B.T.sum(axis=1)
w1, res1, Rank1, sv1=LA.lstsq(A.T, B.T.sum(axis=1))
print('Average price for that country across years')
print(w1)

Average price for that country across years
[ 1060.55288016  9951.13400161  7021.42053684   584.21698168  7366.77811148
  1612.27262877  8041.92583627]


In [6]:
data='Data.xlsx'
data=pd.read_excel(data, sheetname='new')
data
A1=data[data.columns[0:6]]
b1=data[data.columns[6]]
A1.shape

(33, 6)

In [38]:
w2, res2, Rank2, sv1=LA.lstsq(A1, b1)
print('Beef with Years as Dummy Variables')
print(w2)

Beef with Years as Dummy Variables
[  5.19906779e+03  -1.70602041e+07   4.99965247e+07   1.04653784e+08
   3.78669066e+07  -4.26890655e+05]


In [18]:
q, r=np.linalg.qr(A1)
x=np.linalg.solve(r, np.dot(q.T, b1))
x

array([  5.19906779e+03,  -1.70602041e+07,   4.99965247e+07,
         1.04653784e+08,   3.78669066e+07,  -4.26890655e+05])

In [32]:
file='GATSPublish.xls'
x1=pd.read_excel(file, sheetname='2017')
x1=x1.iloc[7:32]
quantities=x1.iloc[0:30, 9:15]
values=x1.iloc[0:30, 15]
quantities
#unit_value=x1.iloc[0:30, 1:7]
#quantity=x1.iloc[0:30,9:15]
#total_value=x1.iloc[0:30,17:23]
#total_value.as_matrix()

Unnamed: 9 Unnamed: 10  Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14
7        3506      239028       108483      3253.5       199346       138544
8      7856.5      101321      38496.4      432946      28632.7       160106
9      8047.1     56682.5      59530.1      5319.3       6552.5      33398.7
10     3947.9      178318       108869     61999.9      18799.5       743535
11     226167  7.9045e+06   3.4247e+06      819321      6848331       959473
12    23293.2     16491.4       979125      3527.9      12074.9       7736.4
13        271      233883  1.07497e+06     54708.3       134814       197195
14     1125.6     27588.6       376015      4270.7      12794.4       459882
15      919.5      9819.7       132292       368.8       1482.9       236866
16    23972.8      278053      96169.1      6900.8      19226.6       119542
17       4260      307553       157600      7829.3       346721       503275
18       11.1     10565.8      60270.2       13945  2.46219e+06       817576
19     3145.4     18245.4      60906.4          80       2152.3       8027.5
20    51582.1      266872       253884     12029.4       125237      34315.5
21    10714.9     51184.6      51907.8      2528.7       1175.6       5068.2
22    64185.5      900486   1.0574e+07      257493      97881.2  1.66914e+06
23    44813.9     56950.5       151752     14971.3      29837.9        96433
24     105240      3438.6      60017.4      269347       1299.4       5272.3
25    11981.1       379.6      58656.2     46208.6       5378.1       190679
26      411.7     12545.4       217730        28.5       286843       198459
27     6200.4     22342.1      56474.9     71862.8       1145.3      29747.4
28    11598.8     27096.7       189483     12196.5       150738      76459.2
29     1465.1      633106       548279      1216.2       4030.3       231083
30      111.9     45371.7       173315       444.7       3426.2       372099
31        NaN         NaN          NaN         NaN          NaN          NaN

In [20]:
w2, Res2, rank2, sv2=LA.lstsq(quantities.as_matrix(),values.as_matrix())
print('The average price for each quantity \n')
print(w2)

NameError: name 'quantities' is not defined

In [113]:
A1

array([[1029.9, 2013],
       [207873.1, 2013],
       [24098.2, 2013],
       [182751.3, 2013],
       [26250.8, 2013],
       [174889.8, 2013],
       [93870.0, 2013],
       [459.8, 2014],
       [360945.6, 2014],
       [20289.2, 2014],
       [204465.1, 2014],
       [29420.1, 2014],
       [198526.7, 2014],
       [115438.2, 2014],
       [307.9, 2015],
       [419497.4, 2015],
       [36651.1, 2015],
       [213333.3, 2015],
       [43884.4, 2015],
       [219698.5, 2015],
       [145771.0, 2015],
       [nan, 2016],
       [255676.5, 2016],
       [37299.3, 2016],
       [247806.5, 2016],
       [38407.9, 2016],
       [202880.5, 2016],
       [182935.9, 2016],
       [nan, 2017],
       [231644.1, 2017],
       [36330.7, 2017],
       [257715.0, 2017],
       [38133.3, 2017],
       [184766.0, 2017],
       [210991.2, 2017]], dtype=object)